name: Generate Stats JSON
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  paths-ignore:
      - 'github-user-stats.json'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate Stats JSON
        uses: LukeHagar/stats-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update github-user-stats.json [skip ci]"
          file_pattern: 'github-user-stats.json'