name: Render GIFs
on:
  push:
    paths:
      - 'github-user-stats.json'
      - 'out/**'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: yarn install

      - name: Render GIFs
        run: yarn render
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GIFs"
          file_pattern: 'out/*.gif'